language: node_js
node_js:
  - "5.0"
  - "4.0"
  - "0.12"
  - "0.10"
services: postgresql
addons:
  postgresql: "9.4"
sudo: false
env:
  - DB_USER=postgres DB_PASS=''
before_script:
  - psql -c 'create database sailspg;' -U postgres
notifications:
  email:
    - particlebanana@gmail.com
